version: '3'

services:
  mariadb:
    container_name: mariadb
    restart: always
    build: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=k2002y1417
      - MYSQL_DATABASE=envdata
      - MYSQL_USER=pi
      - MYSQL_PASSWORD=k2002y1417
    volumes:
      -./mariadb/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"

  mqtt2db:
    build: mqtt2db
    restart: always
    container_name: mqtt2db
    ports:
      - "1883:1883"

  web_server:
    build: web_server
    restart: always
    container_name: web_server
    ports:
      - "5001:5001"
