version: '3.7'

services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/uwsgi.log # app.wsgi のappはDjangoで作成するプロジェクト名
    restart: unless-stopped
    container_name: Django_DjangoProject
    networks:
      - django_net
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: Postgres_DjangoProject
    networks:
      - django_net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=k2002y1417
    volumes:
      - djangoproject.db.volume:/var/lib/postgres
      - ./postgres/init.d:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:1.24
    restart: unless-stopped
    container_name: nginx_DjangoProject
    networks:
      - django_net
    ports:
      - "82:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - python

networks:
  django_net:
    driver: bridge

volumes:
  djangoproject.db.volume:
    name: djangoproject.db.volume
